---
services:
  redis:
    image: redis:alpine
    command: --requirepass ${REDIS_PASSWORD:-password}
    healthcheck:
      test: redis-cli -a ${REDIS_PASSWORD:-password} ping | grep "^PONG$"
    pull_policy: always
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redata:/data
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 64m

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 64m

volumes:
  postgres_data:
  redata:
